[window]
dynamic_padding = true
opacity = 0.95
decorations = "None"
padding = { x = 4, y = 0 }

[font]
normal = { family = 'JetBrains Mono', style = 'Medium' }
size = 11

[general]
import = [
   "~/.config/alacritty/themes/kanagawa_dragon.toml"
]
