[window]
dynamic_padding = true
opacity = 0.95
# padding = { x = 8, y = 8 }
# dimensions = { columns = 160, lines = 50 }
# decorations = "None"
# startup_mode = "Fullscreen"

[font]
normal = { family = 'JetBrains Mono', style = 'Semibold' }
size = 11

[general]
import = [
   "~/.config/alacritty/themes/kanagawa_dragon.toml"
]
