[window]
dynamic_padding = true
opacity = 0.95
decorations = "None"

[font]
normal = { family = 'JetBrains Mono', style = 'Medium' }
size = 12

[general]
import = [
   "~/.config/alacritty/themes/kanagawa_dragon.toml"
]
